<#
.SYNOPSIS
    Creates (or updates) the Entra ID app registration for the SFNC Share Links
    Outlook add-in and writes src\config.js with the resulting IDs.

.DESCRIPTION
    Registers a single-tenant public client (SPA) app with delegated Graph
    permissions: User.Read, Files.ReadWrite.All, Sites.Read.All.
    Redirect URIs cover the MSAL popup fallback and Nested App Authentication
    (brk-multihub).

    Requires the Microsoft.Graph.Applications module and an account that can
    create app registrations (Application Developer role or higher).

.EXAMPLE
    .\2026_06.10_Setup_EntraApp_v1.0.ps1
#>
[CmdletBinding()]
param(
    [string]$DisplayName = "SFNC Share Links (Outlook Add-in)",
    [int]$Port = 3000,
    # Production hosting origin+path, e.g. https://sfncadmin.github.io/sfnc-share-links
    # When set, its redirect URIs are registered alongside localhost so the same
    # app works for both local dev and the hosted (GitHub Pages) deployment.
    [string]$BaseUrl = ""
)

$ErrorActionPreference = "Stop"

if (-not (Get-Module -ListAvailable Microsoft.Graph.Applications)) {
    Write-Host "Installing Microsoft.Graph.Applications module (CurrentUser)..." -ForegroundColor Yellow
    Install-Module Microsoft.Graph.Applications -Scope CurrentUser -Force
}
Import-Module Microsoft.Graph.Applications

Connect-MgGraph -Scopes "Application.ReadWrite.All" -NoWelcome
$ctx = Get-MgContext
$tenantId = $ctx.TenantId
Write-Host "Connected to tenant $tenantId as $($ctx.Account)"

# Resolve delegated permission scope IDs dynamically from the Graph service principal
$graphAppId = "00000003-0000-0000-c000-000000000000"
$graphSp = Get-MgServicePrincipal -Filter "appId eq '$graphAppId'"
$scopeNames = @("User.Read", "Files.ReadWrite.All", "Sites.Read.All")
$resourceAccess = foreach ($name in $scopeNames) {
    $scope = $graphSp.Oauth2PermissionScopes | Where-Object { $_.Value -eq $name }
    if (-not $scope) { throw "Could not resolve Graph delegated permission '$name'." }
    @{ Id = $scope.Id; Type = "Scope" }
}

$spaRedirects = [System.Collections.Generic.List[string]]@(
    "https://localhost:$Port/src/auth-redirect.html",
    "https://localhost:$Port/src/taskpane/taskpane.html",
    "brk-multihub://localhost:$Port"
)
if ($BaseUrl) {
    $base = $BaseUrl.TrimEnd("/")
    $originHost = ([Uri]$base).Host
    $spaRedirects.Add("$base/src/auth-redirect.html")
    $spaRedirects.Add("$base/src/taskpane/taskpane.html")
    $spaRedirects.Add("brk-multihub://$originHost")
    Write-Host "Including production redirect URIs for $base"
}

$appParams = @{
    DisplayName            = $DisplayName
    SignInAudience         = "AzureADMyOrg"
    Spa                    = @{ RedirectUris = $spaRedirects }
    RequiredResourceAccess = @(@{ ResourceAppId = $graphAppId; ResourceAccess = $resourceAccess })
}

$existing = Get-MgApplication -Filter "displayName eq '$DisplayName'" | Select-Object -First 1
if ($existing) {
    Write-Host "Updating existing app registration '$DisplayName'..."
    Update-MgApplication -ApplicationId $existing.Id @appParams
    $app = Get-MgApplication -ApplicationId $existing.Id
} else {
    Write-Host "Creating app registration '$DisplayName'..."
    $app = New-MgApplication @appParams
}

$clientId = $app.AppId
Write-Host "App (client) ID: $clientId" -ForegroundColor Green

# Write src\config.js (gitignored - tenant/machine local)
$configPath = Join-Path (Split-Path $PSScriptRoot -Parent) "src\config.js"
@"
// Generated by setup\2026_06.10_Setup_EntraApp_v1.0.ps1 on $(Get-Date -Format yyyy-MM-dd)
window.SFNC_CONFIG = {
  clientId: "$clientId",
  tenantId: "$tenantId",
  scopes: ["User.Read", "Files.ReadWrite.All", "Sites.Read.All"]
};
"@ | Set-Content -Path $configPath -Encoding utf8
Write-Host "Wrote $configPath" -ForegroundColor Green

Write-Host ""
Write-Host "Next steps:" -ForegroundColor Cyan
Write-Host "  1. Each user consents on first sign-in. To consent for everyone at once, open:"
Write-Host "     https://login.microsoftonline.com/$tenantId/adminconsent?client_id=$clientId" -ForegroundColor Yellow
Write-Host "  2. npm install && npm run certs && npm start"
Write-Host "  3. Sideload manifest.xml (see README.md)."
