<#
.SYNOPSIS
    Creates (or updates) the Entra ID app registration for the SFNC Share Links
    Outlook add-in and writes src\config.js with the resulting IDs.

.DESCRIPTION
    Registers a public client (SPA) app with delegated Graph permissions:
    User.Read, Files.ReadWrite.All, Sites.Read.All, GroupMember.Read.All.

    By default creates a single-tenant app (AzureADMyOrg). Pass -MultiTenant to
    create an app that accepts sign-ins from any Microsoft 365 organization.

    GroupMember.Read.All is required for the optional admin policy feature and
    requires admin consent. The script outputs an admin-consent URL.

    Requires the Microsoft.Graph.Applications module and an account that can
    create app registrations (Application Developer role or higher).

.EXAMPLE
    .\2026_06.10_Setup_EntraApp_v1.0.ps1
    .\2026_06.10_Setup_EntraApp_v1.0.ps1 -MultiTenant -BaseUrl https://sfncadmin.github.io/sfnc-share-links
#>
[CmdletBinding()]
param(
    [string]$DisplayName = "SFNC Share Links (Outlook Add-in)",
    [int]$Port = 3000,
    # Production hosting origin+path, e.g. https://sfncadmin.github.io/sfnc-share-links
    [string]$BaseUrl = "",
    # Allow any Microsoft 365 tenant to sign in (omit tenantId from config.js)
    [switch]$MultiTenant
)

$ErrorActionPreference = "Stop"

if (-not (Get-Module -ListAvailable Microsoft.Graph.Applications)) {
    Write-Host "Installing Microsoft.Graph.Applications module (CurrentUser)..." -ForegroundColor Yellow
    Install-Module Microsoft.Graph.Applications -Scope CurrentUser -Force
}
Import-Module Microsoft.Graph.Applications

Connect-MgGraph -Scopes "Application.ReadWrite.All" -NoWelcome
$ctx = Get-MgContext
$tenantId = $ctx.TenantId
Write-Host "Connected to tenant $tenantId as $($ctx.Account)"

# Resolve delegated permission scope IDs dynamically from the Graph service principal
$graphAppId = "00000003-0000-0000-c000-000000000000"
$graphSp = Get-MgServicePrincipal -Filter "appId eq '$graphAppId'"
$scopeNames = @("User.Read", "Files.ReadWrite.All", "Sites.Read.All", "GroupMember.Read.All")
$resourceAccess = foreach ($name in $scopeNames) {
    $scope = $graphSp.Oauth2PermissionScopes | Where-Object { $_.Value -eq $name }
    if (-not $scope) { throw "Could not resolve Graph delegated permission '$name'." }
    @{ Id = $scope.Id; Type = "Scope" }
}

$spaRedirects = [System.Collections.Generic.List[string]]@(
    "https://localhost:$Port/src/auth-redirect.html",
    "https://localhost:$Port/src/taskpane/taskpane.html",
    "brk-multihub://localhost:$Port"
)
if ($BaseUrl) {
    $base = $BaseUrl.TrimEnd("/")
    $originHost = ([Uri]$base).Host
    $spaRedirects.Add("$base/src/auth-redirect.html")
    $spaRedirects.Add("$base/src/taskpane/taskpane.html")
    $spaRedirects.Add("brk-multihub://$originHost")
    Write-Host "Including production redirect URIs for $base"
}

$appParams = @{
    DisplayName            = $DisplayName
    SignInAudience         = if ($MultiTenant) { "AzureADMultipleOrgs" } else { "AzureADMyOrg" }
    Spa                    = @{ RedirectUris = $spaRedirects }
    RequiredResourceAccess = @(@{ ResourceAppId = $graphAppId; ResourceAccess = $resourceAccess })
}

$existing = Get-MgApplication -Filter "displayName eq '$DisplayName'" | Select-Object -First 1
if ($existing) {
    Write-Host "Updating existing app registration '$DisplayName'..."
    Update-MgApplication -ApplicationId $existing.Id @appParams
    $app = Get-MgApplication -ApplicationId $existing.Id
} else {
    Write-Host "Creating app registration '$DisplayName'..."
    $app = New-MgApplication @appParams
}

$clientId = $app.AppId
Write-Host "App (client) ID: $clientId" -ForegroundColor Green

# Write src\config.js (gitignored - tenant/machine local)
$configPath = Join-Path (Split-Path $PSScriptRoot -Parent) "src\config.js"
if ($MultiTenant) {
    $configContent = @"
// Generated by setup\2026_06.10_Setup_EntraApp_v1.0.ps1 on $(Get-Date -Format yyyy-MM-dd)
// Multi-tenant: any Microsoft 365 organization can sign in.
window.SFNC_CONFIG = {
  clientId: "$clientId",
  scopes: ["User.Read", "Files.ReadWrite.All", "Sites.Read.All", "GroupMember.Read.All"]
};
"@
} else {
    $configContent = @"
// Generated by setup\2026_06.10_Setup_EntraApp_v1.0.ps1 on $(Get-Date -Format yyyy-MM-dd)
window.SFNC_CONFIG = {
  clientId: "$clientId",
  tenantId: "$tenantId",
  scopes: ["User.Read", "Files.ReadWrite.All", "Sites.Read.All", "GroupMember.Read.All"]
};
"@
}
$configContent | Set-Content -Path $configPath -Encoding utf8
Write-Host "Wrote $configPath" -ForegroundColor Green

Write-Host ""
Write-Host "Next steps:" -ForegroundColor Cyan
Write-Host "  1. Grant admin consent for GroupMember.Read.All (required for the policy feature):"
Write-Host "     https://login.microsoftonline.com/$tenantId/adminconsent?client_id=$clientId" -ForegroundColor Yellow
Write-Host "  2. (Optional) Create an 'SFNC_ShareLinks_Policy' SharePoint list on your root site"
Write-Host "     with text columns Title and SettingValue to configure per-tenant link policies."
Write-Host "  3. npm install && npm run certs && npm start"
Write-Host "  4. Sideload manifest.xml (see README.md)."
